### ISSUE TITLE
Custom fields provided by KPEntryTemplates plugin are not shown in Options dialog

### ISSUE THREAD

**Issue by Vitriia** [cristianst85/QuickConnectPlugin#10]
Hi,
I have dl your plugin in v 4.0RC2 yesterday.
So i do not manage to parametrize 😢 
Maybe it's because my fields are in Template (from Entry Templates for KeePass by Mitch Capper). But my fields are into avanced tab too.

Can you help me or export your sample ?

Windows 10
KeePass 2.34
.Net Framework 4

P.s: Sorry for my bad english :'(

**Comment by wanderleihuttel** [comment]
Take a look.
![quickconnect](https://cloud.githubusercontent.com/assets/16232272/18965948/abc02136-8655-11e6-85b5-45f9d6f08110.png)

**Comment by Vitriia** [comment]
It works but not with Custom fields

**Comment by cristianst85** [comment]
<s>I've installed KPEntryTemplates and the fields provided by template are showing up in the drop-down list.</s>

Edit: 29/11/2016
@Vitriia, you were right. Custom fields provided by KPEntryTemplates are listed only if there is at least one entry that has the template parent set.

**Comment by cristianst85** [comment]
@Vitriia, feedback?

**Comment by Vitriia** [comment]
I have try with some custom fields (Connection method and _etm_position_*****) and it don't work :/
One of my tests: 
- I set a template with _etm_position_connect custom field
- I set QC option with url as host adress and my custom field as connection method
- I enter ssh into the field and an adress into the url no changes
- So if i modify my custom field with "note" field and modify QC option it work.

**Comment by cristianst85** [comment]
I think you need to map to the template Field Name (i.e. _CustomFieldName_ in my case). I'm not sure why the fields starting with __etm_ are showing in the drop-down list.

![01-kp-template](https://cloud.githubusercontent.com/assets/12585988/20582554/c0beb672-b1ea-11e6-9413-015be1b8a5a3.png)
![02-kp-entry](https://cloud.githubusercontent.com/assets/12585988/20582552/c0be5772-b1ea-11e6-8cd9-c9f2effb3975.png)
![03-kp-mapping](https://cloud.githubusercontent.com/assets/12585988/20582553/c0beba6e-b1ea-11e6-93ec-8643e0ec4850.png)
![04-kp-qc-context-menu](https://cloud.githubusercontent.com/assets/12585988/20582555/c0c2a318-b1ea-11e6-8cb9-29be2b27acf1.png)

**Comment by cristianst85** [comment]
I'm working on a fix for this. Also, I've updated my comment [here](https://github.com/cristianst85/QuickConnectPlugin/issues/10#issuecomment-250549869).

**Comment by cristianst85** [comment]
@Vitriia, it should work now. Could you try this [build](http://www.disruptivesoftware.ro/projects/QuickConnectPlugin/nightly/0.4.0-rc.2-20161130-97011b7/)?

Also, I've filtered out from the drop-down list the fields that begin with _etm_.

![01-kp-template-custom-fields](https://cloud.githubusercontent.com/assets/12585988/20759925/1b1a145e-b727-11e6-89d0-50564a4cc9b7.png)
![02-kp-advanced](https://cloud.githubusercontent.com/assets/12585988/20759928/1b273300-b727-11e6-9df6-51c7bba9caec.png)
![03-kp-quickconnect-options](https://cloud.githubusercontent.com/assets/12585988/20759926/1b2159a8-b727-11e6-87e7-20032ceafbcc.png)
![04-kp-quickconnect-entry-menu](https://cloud.githubusercontent.com/assets/12585988/20759927/1b21cf64-b727-11e6-88d2-4437f918cf11.png)
