### ISSUE TITLE
Possibility to load sessions saved from putty

### ISSUE THREAD

**Issue by wanderleihuttel** [cristianst85/QuickConnectPlugin#12]
Hello. 
Should be interesting if would be possible to run sessions from Putty, because by default putty use default charset as ISO8859-1 and many servers are UTF8. 
Example: 
putty -load "Putty Session Name" -l root -pw password

Commands
https://the.earth.li/~sgtatham/putty/0.67/puttydoc.txt

**Comment by cristianst85** [comment]
Hi!
Please check this https://github.com/cristianst85/QuickConnectPlugin/issues/2#issuecomment-209572373

**Comment by wanderleihuttel** [comment]
Thanks Cristian

Should be interesting include this information in readme.

Best Regards

_Wanderlei Hüttel_

2016-09-29 15:53 GMT-03:00 Cristian Stoica notifications@github.com:

**Comment by cristianst85** [comment]
I know that this is somewhat confusing, but we are now on the [dev](https://github.com/cristianst85/QuickConnectPlugin/tree/dev) branch. Maybe I should set it as default.

Please let me know if that works for what you need. Thanks!
