### ISSUE TITLE
Allow mRemoteNG integration

### ISSUE THREAD

**Issue by magmax** [cristianst85/QuickConnectPlugin#13]
In order to allow tabs, it should be helpfull to allow mRemoteNG integration.

It could create a connection file and then run mRemoteNG with that connection file.

It may be unsecure, but useful.

**Comment by cristianst85** [comment]
Tabs? I'm not familiar with mRemoteNG.

**Comment by magmax** [comment]
mRemoteNG is a RDP free client, but it has tabs.

After thinking about it for a while, I think this should not be a KeePass action. It should be a mRemoteNG plugin, in order to use KeePass passwords, so I close this issue.
