### ISSUE TITLE
Additional parameters not working.

### ISSUE THREAD

**Issue by magmax** [cristianst85/QuickConnectPlugin#14]
I need the additional parameters option in order to:

- Use ssh credentials file instead of user/password
- change the connection port.

But I am not able to make it work. After browsing the code (QuickConnectPluginSettings.cs), I think it is not implemented. Am I wrong? Should I write any magic key in my notes in order to use them?

**Example:**

Currently I'm using the full line like this with password:
`cmd://putty -load "Default Settings" 127.0.0.1 -l {USERNAME} -pw {PASSWORD}`
I suppose it is similar to the line executed with QuickConnect. But for some hosta I need something like:
`cmd://putty -load "Default Settings" 127.0.0.1 -P 2672 -i c:\whatever\foo.ppk -l my_user`

**Comment by cristianst85** [comment]
Hi, @magmax. 

At the moment only `port` parameter is supported. Please, see the [usage](https://github.com/cristianst85/QuickConnectPlugin/tree/dev#usage) on dev branch.

**Comment by cristianst85** [comment]
Could you try this [build](http://www.disruptivesoftware.ro/projects/QuickConnectPlugin/nightly/0.4.0-rc.2-20161124-266baf3/)?

Add to the field that is mapped to _Additional options_ something like this:
`ssh;port:2672;key:"c:\whatever\foo.ppk"`

Also, if you need to load a session:
`ssh;session:"Default Settings";port:2672;key:"c:\whatever\foo.ppk"`

**Comment by magmax** [comment]
It worked perfectly well. 
I only tried the key option, because I'm using the default port 22 for SSH.

**Comment by magmax** [comment]
By the way... Does the "port" option work with RDP?

**Comment by cristianst85** [comment]
No. You can try to put the port right after the ip address (i.e. `ipAddress:port`). But, this will probably break the password changing feature.

See [mstsc command syntax](https://technet.microsoft.com/en-us/library/cc753907(v=ws.11).aspx).
