### ISSUE TITLE
Take port numbers from host address

### ISSUE THREAD

**Issue by moose999** [cristianst85/QuickConnectPlugin#15]
I have SSH servers that run on non-standard ports. I store host addresses in my URL field like hostname:port. Please can you read the port number as well at the FQDN?

**Comment by cristianst85** [comment]
Can you give me some concrete examples?

Thank you.

**Comment by SirScythe** [comment]
I'd love that too, 

> Can you give me some concrete examples?

for example if ssh is running on port 1234 you change the URL field to example.com:1234 and putty connects to example.com over port 1234

**Comment by moose999** [comment]
Many guides recommend changing SSH ports to reduce logfile clutter, so it should be a common request. As you mentioned on another feature request, [this plugin](https://github.com/aalbng/AdvancedConnectPlugin) should be able to do it.

**Comment by cristianst85** [comment]
Hey guys, you should try this [build](http://www.disruptivesoftware.ro/projects/QuickConnectPlugin/nightly/0.4.0-rc.2-20170221-fb4fe94/).

**Comment by moose999** [comment]
Works for me - thanks!
