### ISSUE TITLE
Launch WinSCP using a password with the "vertical bar" character

### ISSUE THREAD

**Issue by marc0l92** [cristianst85/QuickConnectPlugin#19]
If the password used to access the remote server using WinSCP contains the special character | (vertical bar) the command is not executed correctly or it does not contains the remote URL.

**Example 1 - Vertical bar in the middle of the password**
_Entry_
Title: My server
User Name: admin
Password: aaaa|aaaa
URL: 192.168.1.11
Note: ssh

_**Result:** WinSCP does not start_

**Example 2 - Vertical bar at the end of the password**
_Entry_
Title: My server
User Name: admin
Password: aaaaaa|
URL: 192.168.1.11
Note: ssh

_**Result:** Command executed: winscp.exe scp://admin:aaaaaa_
_The command does not contain the vertical bar and the URL_

**Comment by cristianst85** [comment]
I've just released version [0.4.2](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.4.2) that fixes the addressed issue.

Thank you.

**Comment by marc0l92** [comment]
Thank you for this very useful plugin
