### ISSUE TITLE
Shortcut keys to access function

### ISSUE THREAD

**Issue by salvorapi** [cristianst85/QuickConnectPlugin#23]
I think that a great feature can be to implement shortcut keys for access menu function.

Thank you.

Salvo.

**Comment by cristianst85** [comment]
Hi Salvo,

Could you please be more specific about this request?

Thanks,

**Comment by salvorapi** [comment]
I use your plugin because it's easy access a VM via Putty or WinSCP with credentials stored on KeePass.

But for run Putty or WinSCP over an item I need to open drop-down menu first.

A shortcut key for Putty (SHIFT+ALT+P for example) or  WinSCP (SHIFT+ALT+W) can reduce time for access a VM .

Thank you.

Salvo.

**Comment by pickeld** [comment]
totally agree with @salvorapi

**Comment by cristianst85** [comment]
I'll look into it.

**Comment by cristianst85** [comment]
I know this is long overdue, but can someone test it to see if it's working as expected?

https://github.com/cristianst85/QuickConnectPlugin/files/3428862/QuickConnectPlugin-0.5.2-20190725-e6b084b.zip
