### ISSUE TITLE
Change password does not work for non-root users

### ISSUE THREAD

**Issue by brakkio86** [cristianst85/QuickConnectPlugin#24]
Change password on  RHEL does not work and I receive this error:
![immagine](https://user-images.githubusercontent.com/25152/33560166-419a4bfc-d90f-11e7-8ea2-b609154aeac4.png)

If I use the batch password changer, I see this log:
[2017-12-04 16:22:40] System.Exception: Error changing password. Expected 'New Password' string/pattern from shell, but got null.
   in QuickConnectPlugin.PasswordChanger.LinuxPasswordChanger.processShellStream(ShellStream shellStream, String expectedPattern)
   in QuickConnectPlugin.PasswordChanger.LinuxPasswordChanger.ChangePassword(String host, String username, String password, String newPassword)
   in QuickConnectPlugin.PasswordChanger.LinuxPasswordChangerEx.ChangePassword(IHostPwEntry hostPwEntry, String newPassword)
   in QuickConnectPlugin.PasswordChanger.Services.PasswordChangerService.ChangePassword(IHostPwEntry hostPwEntry, String newPassword)
   in QuickConnectPlugin.PasswordChanger.BatchPasswordChangerWorker.OnRun()

Can you solve this issue?

Thanks,
Francesco

**Comment by cristianst85** [comment]
Hi @brakkio86,

Thank you for reporting this issue.

Connect to your server using a SSH client (e.g. PuTTY) and try to change the password by issuing the `passwd` command. Copy-paste your server response here or if that could be a security issue send me an email (you can find it by accessing the _QuickConnectPlugin_ from KeePass > _About_ dialog).

A typical server response to `passwd` command would be something like this:

`dev:~ # passwd`
`New password:`
`BAD PASSWORD: it is too simplistic/systematic`
`Retype new password:`
`passwd: password updated successfully`
`dev:~ #`

**Comment by brakkio86** [comment]
Hello,

I'm using RedHat EL 6.x server and password change is made by the user, not
by root (as shown in your example). I've just change the user and
servername to hide the real one, but here you have the output:
[USER@SERVER ~]$ passwd
Changing password for user USER.
Changing password for USER.
(current) UNIX password:
New password:
Retype new password:
passwd: all authentication tokens updated successfully.

Thanks,
Francesco



2017-12-06 21:55 GMT+01:00 Cristian Stoica <notifications@github.com>:
