### ISSUE TITLE
Pre-authentication for RDP

### ISSUE THREAD

**Issue by nikagl** [cristianst85/QuickConnectPlugin#25]
Hi,

Thanks for a great plugin! :)

Works for most of my RDP sessions. One location though requires you to pre-authenticate before the RDP connection is made. When using mstsc.exe that is done automatically (before connecting it popsup an authentication message and as soon as you enter details it opens RDP and automatically logs in), but when using QuickConnect from Keepass it says the connection cannot be made...

Using RDP:
![image](https://user-images.githubusercontent.com/1291517/37836644-49983856-2eb3-11e8-8695-1be48cccfcc7.png)
![image](https://user-images.githubusercontent.com/1291517/37836731-8109e758-2eb3-11e8-93ad-fd422efdad05.png)
![image](https://user-images.githubusercontent.com/1291517/37836757-981649e6-2eb3-11e8-8899-cb983b6d9c89.png)
![image](https://user-images.githubusercontent.com/1291517/37836794-b3561c5e-2eb3-11e8-81cb-6b27b83f9d12.png)
![image](https://user-images.githubusercontent.com/1291517/37836832-d6f8bd4c-2eb3-11e8-8c59-302bb0f251f2.png)

Using QuickConnect plugin:
![image](https://user-images.githubusercontent.com/1291517/37836771-a06d73c6-2eb3-11e8-9261-e6c85f51aa7c.png)
![image](https://user-images.githubusercontent.com/1291517/37836855-e7af3486-2eb3-11e8-8e52-7665036635fd.png)

Regards,

Nika.

**Comment by cristianst85** [comment]
Hi, @nikagl.

Thank you for your feedback!

Unfortunately is hard for me to say why this is not working :(

For _Remote Desktop_ the plugin does the following:
1) Stores the credentials into _Windows Vault_ (_Control Panel_ > _Credential Manager_):
`cmdkey.exe /generic:TERMSRV/{ipAddress} /user:{username} /pass:{password}`
2) Launches _Remote Desktop Connection_:
`mstsc.exe /v:{ipAddress} /f`
For _console_ entry the `/admin` or `/console` switch it added.
3) Deletes the credentials from _Windows Vault_ after 5 seconds:
`cmdkey.exe /delete:TERMSRV/{ipAddress}`

Steps 2) and 3) are initiated simultaneously and it's possible that if Remote Desktop Connection cannot establish a connection with the remote server within the given interval (i.e. 5 seconds) the credentials are removed from the vault (Step 3) before Remote Desktop Connection can retrieve them.

Given your example, if you delay for more than 5 seconds the confirmation when the _certificate dialog_ pops-up then the credentials will be removed before Remote Desktop Connection can retrieve them.


You should try to reproduce this issue by running the above commands manually (without the step 3).

Regards,
Cristian

**Comment by nikagl** [comment]
Hi Cristian,

Thanks for the details. I'll test it when I am at the location where it fails, and let you know in which bit it fails. For me it looks like it fails when RDP is setting up the connection and needs to know whether it's allowed to do that and uses somekind of pre-authentication, but I have not found details about how that works in RDP. So maybe using your commands give me some more insight, I'll let you know asap.

Regards,

Nika.

**Comment by nikagl** [comment]
Ok... user error....sorry, will close this ticket. It was caused by the person between keyboard en display because he used the wrong account... sorry again (nevertheless good to know how it works :) )
