### ISSUE TITLE
not compatible anymore with Keepass 2.40

### ISSUE THREAD

**Issue by GroteVriendelijkeReus** [cristianst85/QuickConnectPlugin#26]
As of Keepass 2.40, the dll isn't compatible anymore.
Below you may find the error shown. 
![keepass](https://user-images.githubusercontent.com/12912050/45595449-56687580-b9ac-11e8-9f15-a90170b9839a.jpg)

os: win 10 x64

**Comment by cristianst85** [comment]
Hi @GroteVriendelijkeReus,

Thank you for reporting this issue.

Please use the .plgx version as a workaround if that's possible until I have some time to look into this.

**Comment by cristianst85** [comment]
A fix will be provided soon.

Meanwhile another **workaround** would be to copy **Renci.SshNet.dll** ([download here](https://github.com/cristianst85/QuickConnectPlugin/blob/master/libs/Renci.SshNet.dll)) to KeePass Plugins directory.

![keepass_2 40_quickconnectplugin_workaround](https://user-images.githubusercontent.com/12585988/45919365-e4f16100-be9c-11e8-8037-9571c0f47cc6.png)

For future reference: [Plugin Compatibility Check](https://sourceforge.net/p/keepass/discussion/329220/thread/3c8b8128/)

**Comment by GroteVriendelijkeReus** [comment]
> 
> 
> A fix will be provided soon.
> 
> Meanwhile another **workaround** would be to copy **Renci.SshNet.dll** ([download here](https://github.com/cristianst85/QuickConnectPlugin/blob/master/libs/Renci.SshNet.dll)) to KeePass Plugins directory.
> 
> ![keepass_2 40_quickconnectplugin_workaround](https://user-images.githubusercontent.com/12585988/45919365-e4f16100-be9c-11e8-8037-9571c0f47cc6.png)
> 
> For future reference: [Plugin Compatibility Check](https://sourceforge.net/p/keepass/discussion/329220/thread/3c8b8128/)

Thank you so far!

**Comment by cristianst85** [comment]
I've just released version [0.4.4](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.4.4) that fixes the addressed issue.
