### ISSUE TITLE
Pass custom command line arguments to Putty

### ISSUE THREAD

**Issue by cyberknet** [cristianst85/QuickConnectPlugin#27]
I'd like to pass custom command line arguments to Putty when launching to configure SSH port forwarding. The current set up does not appear to do this.

Steps to reproduce:

1. I set up QuickConnect to use a custom field for "Additional options from" - field name "options"
2. I populated the custom field for an entry with the requisite putty options.
3. I right clicked the entry and launched Putty bu selecting "Open Putty Console" option
4. When observing the settings for the current session, no forwarded ports are configured.
5. Verify via powershell that the command line argument was not passed in by running Get-WmiObject Win32_Process -filter "name='putty.exe'" | select CommandLine
5. Observation - the command line parameter was not passed to putty

Also per documented security consideration warnings, I do see that my password is being passed on the command line to Putty. This is pretty undesirable for me since I use agent authentication, and so my password is going to be rejected by the server anyway... it would be great for an option to disable this behavior.

**Comment by cristianst85** [comment]
Hi @cyberknet,

The supported arguments (_session type_, _session_, _port_, _ssh_key_) for Putty are quite limited as you already found out. I not sure what you are trying to do as I'm not that familiar with your use case. Can you give some concrete examples?

As for the second issue, do you want that password passing for Putty to be disabled globally, or per entry? Can you point me to any documentation on how to enable/use agent authentication.

Regards,

**Comment by cyberknet** [comment]
Hi @cristianst85,

Agent authentication is actually working just fine after the password authentication fails. I just need to disable the password from being sent. Globally would be fine for me as I use cert-based login everywhere... but I imagine some people aren't so lucky due to company policy, etc.

I can give you a concrete example of the argument I want to pass to Putty... but just a note that what I would really appreciate is the ability to pass in an arbitrary string that is appended to the command line arguments. I could see that this would be useful regardless of if it was Putty, RDP, vSphere if someone had some customization they preferred.

Example I am using:
-L 5555:127.0.0.1:5432

This will tunnel all requests from my local machine on port 5555 to port 5432 on _localhost of the machine I am connecting to_.

I do this to connect to services that are not exposed to the outside world, and it is handy to have the credentials stored in KeePass. Note: For a fantastic plugin for KeePass to accomplish agent, see KeeAgent which is a great replacement for Pageant.

Thank you so much for the rapid response! I really appreciate it. Hope this explanation helps... please let me know if I can give any more detail.

**Comment by cyberknet** [comment]
Is there any more information I can provide to help out here? If you point me in the right direction, I could look at providing a patch myself.

**Comment by cristianst85** [comment]
Sorry about that, but I had some crazy weeks. :(
I'll try to come up with something in the next following days.

**Comment by cyberknet** [comment]
Sad to hear about your troubling time. I am happy to help out if you like, just let me know how, point me in the right direction and I will get to work. Appreciate the plugin and everything you have done with it!

**Comment by cristianst85** [comment]
I created a WIP branch [wip-custom-command-line-args-putty](https://github.com/cristianst85/QuickConnectPlugin/tree/wip-custom-command-line-args-putty).

New setting '**Disable CLI password for Putty**' was added to disable password being sent via command line arguments for Putty.

![image](https://user-images.githubusercontent.com/12585988/47944633-6bba4480-df05-11e8-8db2-dfb3babde1d9.png)

New _command_ option is supported in the **Additional options** field to pass custom command to Putty. The custom command is appended as it is (no escaping using double-quotes is made), but KeePass [placeholders](https://keepass.info/help/base/placeholders.html) are supported.

For example:
`ssh;command:-L 5555:127.0.0.1:5432`

If '**Disable CLI password for Putty**' is checked then you can override this for a specific entry
`ssh;command:-pw {PASSWORD}`

or using quotes if the password contains blanks
`ssh;command:-pw "{PASSWORD}"`

or without using placeholders
`ssh;command:-pw 12345678` (**this is not recommend**)

or with multiple switches
`ssh;command:-L 5555:127.0.0.1:5432 -pw {PASSWORD}`

**NOTE:** If `-pw` switch is present in the _command_ option then this take precedence over whether '**Disable CLI password for Putty**' is checked or not, meaning that the password will always be send via command line arguments.

More possible usages:

Both port and password switch specified with _command_ option
`ssh;command:-P 2222 -pw {PASSWORD}`  (**this breaks the password changing as port is not correctly detected - need to be fixed**)

which is equivalent with
`ssh;port:2222;command:-pw {PASSWORD}`

**NOTE**: _port_ option should not be mixed with `-P` switch in the _command_ option. Probably is better to specify the port along with the host address in the **Host address** field, e.g.: ``linuxhost:2222``.

Here's a preview version for testing: [QuickConnectPlugin-0.5.1-preview.1-20181103-caddaea.zip](https://github.com/cristianst85/QuickConnectPlugin/files/2544461/QuickConnectPlugin-0.5.1-preview.1-20181103-caddaea.zip)

**Comment by cristianst85** [comment]
@cyberknet, have you had any chance to test the preview release?

**Comment by cyberknet** [comment]
Sorry @cristianst85 ... I missed your comment. I am installing it now and will give you feedback by the end of the day. I do apologize for wasting two weeks of your time after you put in the effort to meet my feature request.

**Comment by cyberknet** [comment]
Just tested both of these features. I verified the password is not send on the command line when the option is selected. passing custom command line arguments is working perfectly! This is a great implementation for what i needed, thank you!

**Comment by cristianst85** [comment]
No worries. I'll keep this open until the end of next week, then I'll merge it to _master_.

Please let me know if it needs some additional fine-tuning :)
