### ISSUE TITLE
Greyed out menu option 

### ISSUE THREAD

**Issue by techie2000** [cristianst85/QuickConnectPlugin#28]
I've configured the hostname and connection method mappings, and can see the additional right-click options appear on entries where these fields have been entered. However, the "Open ____" options are greyed out/unusable. This differs to entries where I have not defined the connection method where the right-click option to "Open" is not available, ie the plugin is recognising my mappings.

Running against KeePass v2.42.1

**Comment by cristianst85** [comment]
Hi @techie2000,

What operating system are you using KeePass on?
Are you using any other plugins?

Other things to check:
 - is Putty/WinSCP installed/configured (see QuickConnect Options > General tab > SSH Client Path/WinSCP Path; both paths can be left blank if applications are installed in their default directory, i.e. _Program Files_)
 - _Host address_ needs to be mapped to a different field than _Connection method_ and _Additional options_;

**Comment by cristianst85** [comment]
Hello @techie2000, did you figure it already or are you still experiencing this issue?

**Comment by techie2000** [comment]
> What operating system are you using KeePass on?
Win10

> Are you using any other plugins?
No, this is my first

>     * is Putty/WinSCP installed/configured (see QuickConnect Options > General tab > SSH Client Path/WinSCP Path; both paths can be left blank if applications are installed in their default directory, i.e. _Program Files_)
These were not set (as I was trialling the plugin with rdp. I have now added these paths, but see the same results.

>     * _Host address_ needs to be mapped to a different field than _Connection method_ and _Additional options_;

This was the key one... I was (stupidly) expecting it to be picked up from the Title field (all my connections are setup such that Title = hostname). Having returned to this in a fresh light, I can't believe I ever thought that would work!

Thanks for the follow-up, and thanks for producing the plugin
