### ISSUE TITLE
WinSCP - password must be URL encoded

### ISSUE THREAD

**Issue by ben12** [cristianst85/QuickConnectPlugin#29]
Password must be URL encoded.

One of my password contains a slash "/", it must be replaced by "%2F" in the command to work. 
`"C:\WinSCP\WinSCP.exe"  scp://dev:"my/password"@192.1681.1`
must be:
`"C:\WinSCP\WinSCP.exe"  scp://dev:"my%2Fpassword"@192.1681.1`

**Comment by cristianst85** [comment]
Hi @ben12,

Thank you for reporting this. I'll post an update in the following days with the fix.

Cristian,

**Comment by cristianst85** [comment]
This version should fix your current issue with the encodings, can you test it?

Please note that this release also includes fixes for issues #23 and #27.

[QuickConnectPlugin-0.5.2-20190725-e6b084b.zip](https://github.com/cristianst85/QuickConnectPlugin/files/3428862/QuickConnectPlugin-0.5.2-20190725-e6b084b.zip)

**Comment by ben12** [comment]
It works fine now. Thanks !

**Comment by mabroukb** [comment]
Hello,
I too tested it with single and double quote in passwords. 
It works fine !
