### ISSUE TITLE
Issue with using Field References

### ISSUE THREAD

**Issue by wsniegowski** [cristianst85/QuickConnectPlugin#3]
When trying to pass a field reference as a username / password putty receives the text of the stored reference call instead of receiving data from the referenced entry.  e.g. when trying to use {REF:U@T:SomeEntry} putty sees {REF:U@T:SomeEntry} instead of the value stored  at U@T:SomeEntry.

**Comment by cristianst85** [comment]
Hi, @wsniegowski. Thank you for reporting this. The issue is fixed now in the latest release.

**Comment by wsniegowski** [comment]
Awesome.  I'll update and give it a try.  Looks very promising to use as a
replacement for me for mRemoteNG.  Thank you!
