### ISSUE TITLE
Putty encoding password

### ISSUE THREAD

**Issue by mabroukb** [cristianst85/QuickConnectPlugin#30]
Hi,

I have single quote and double quote in password for connecting to ssh servers.
The argument formater for putty doesnt handle this.

I found that using HttpUtility.JavaScriptStringEncode method, one can escape those caracters.

Can you use this method or find a more appropriate one ?

Thank you,

**Comment by mabroukb** [comment]
By the way, I tried the package from the issue  https://github.com/cristianst85/QuickConnectPlugin/issues/29 and found that it can handle winscp but not putty argument.

And the winscp argument formatter uses urlencoding but putty cannot handle url encoded characters.

**Comment by cristianst85** [comment]
Hi @mabroukb, let me look into this.

**Comment by cristianst85** [comment]
From what I can tell the only issue is with double-quotes ("). Can you please test this version?

[QuickConnectPlugin-0.5.2-20190821-e6262d0.zip](https://github.com/cristianst85/QuickConnectPlugin/files/3524235/QuickConnectPlugin-0.5.2-20190821-e6262d0.zip)

**Comment by mabroukb** [comment]
It works fine.
Thank you !
