### ISSUE TITLE
GeneratedAssemblyInfo.cs, where is this file obtained?

### ISSUE THREAD

**Issue by lxitdn** [cristianst85/QuickConnectPlugin#31]
![QQ截图20200226204528](https://user-images.githubusercontent.com/16263881/75346152-0f88ea00-58d9-11ea-993a-1e6307b77367.jpg)

![6](https://user-images.githubusercontent.com/16263881/75346586-01879900-58da-11ea-878c-54d8a347aa41.jpg)

Hello author,

I want to translate your code plug-in into my native language, but it prompts me that this file is missing when compiling, how should I get this file

**Comment by cristianst85** [comment]
GeneratedAssemblyInfo.cs is auto-generated when the solution is being built.

From the error you got it seems that the VS build tools cannot find **git.exe**.

![image](https://user-images.githubusercontent.com/12585988/76144687-9ed98e80-608b-11ea-8786-2b5f8ba1e797.png)

**Comment by lxitdn** [comment]
What should I do? I am stuck here now

**Comment by cristianst85** [comment]
First make sure you have [Git for Windows](https://gitforwindows.org/) installed.

To test this open a `cmd` and type `git --version`.

If git is properly installed then it should display the current git version installed on your machine.

e.g.: `git version 2.24.1.windows.2`

**Comment by cristianst85** [comment]
@lxitdn, have you managed to solve this issue?
