### ISSUE TITLE
Support keepass 2.45

### ISSUE THREAD

**Issue by xeropresence** [cristianst85/QuickConnectPlugin#32]
Keepass 2.45 throws an exception when attempting to load the plugin

Recompiling against the latest executable resolved the issue.

Resolved by https://github.com/cristianst85/QuickConnectPlugin/pull/33

**Comment by cristianst85** [comment]
It seems that only the dll version is affected.

I'm attaching the error here for further reference.
![image](https://user-images.githubusercontent.com/12585988/81349510-c9b28400-90c8-11ea-933f-40e87b14bf47.png)

**Comment by cristianst85** [comment]
Version [0.5.3](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.5.3) was published. 

Thank you!
