### ISSUE TITLE
Incompatibility with the SCP protocol in WinSCP

### ISSUE THREAD

**Issue by TheRaf974** [cristianst85/QuickConnectPlugin#35]
Hi, 

I'm experimenting an issue with the plugin when I try to connect a WinSCP session.
The server which I'm trying to connect to, doesn't work with the SCP protocol but with SFTP protocol, yes.

In [WinScpArgumentsFormatter.cs](https://github.com/cristianst85/QuickConnectPlugin/blob/3e04d167b99782a26750e510e53d1bb4ee92b084/QuickConnectPlugin/ArgumentsFormatters/WinScpArgumentsFormatter.cs#L19), the SCP protocol is hard coded.

Is it possible to add an optionnal argument to select the SFTP protocol instead of SCP protocol ?

Regards

**Comment by cristianst85** [comment]
Hello.

I will look into it tomorrow.

**Comment by cristianst85** [comment]
Hello. 

I've just implemented your request in the latest release candidate [0.6.0-rc.1](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.6.0-rc.1). You can specify the `protocol` via the additional options (e.g., `protocol:sftp`), if omitted it defaults to `scp`. 

Let me know if this works for you.

Best regards,
Cristian

**Comment by TheRaf974** [comment]
I just tried it and it works.
Thanks for the feature @cristianst85 !!!
