### ISSUE TITLE
WinSCP Error when connect to ftp host  pre-entered password

### ISSUE THREAD

**Issue by feelnrg** [cristianst85/QuickConnectPlugin#36]
First at all. Thank you for development and support for this great plugin.

Issue:

WinSCP usage for domain webspace ftp result:

Authenticating With pre-entered password.
Access denied.

When I use the the gui in fact it works without issues.

![image](https://github.com/cristianst85/QuickConnectPlugin/assets/45741845/1e16d234-be94-472e-be09-25eb583f63a3)

for some reason it brings the error message by using the Plugin with the same credentials from Keepass:
![image](https://github.com/cristianst85/QuickConnectPlugin/assets/45741845/a14c23df-1531-4a02-a30b-9f656f420770)

As you can see there is another promt for the password. But after entering again the same error results.

I have tested plugin v.0.5.3
and also with pre.r. v0.6
Server is: All-inkl (kasserver.com)

Log:
`! 2023-05-11 16:16:15.347 Using username "UserXY".
. 2023-05-11 16:16:15.391 Detected network event
. 2023-05-11 16:16:15.391 Enumerating network events for socket 1412
. 2023-05-11 16:16:15.391 Enumerated 1 network events making 1 cumulative events for socket 1412
. 2023-05-11 16:16:15.391 Handling network read event on socket 1412 with error 0
. 2023-05-11 16:16:15.391 Waiting for the server to continue with the initialization
. 2023-05-11 16:16:15.391 Looking for incoming data
. 2023-05-11 16:16:15.391 Looking for network events
. 2023-05-11 16:16:15.391 Server offered these authentication methods: publickey,password
. 2023-05-11 16:16:15.391 Prompt (password, "SSH password", <no instructions>, "&Password: ")
. 2023-05-11 16:16:15.391 Using stored password.
. 2023-05-11 16:16:15.413 Sent password
. 2023-05-11 16:16:18.008 Detected network event
. 2023-05-11 16:16:18.008 Enumerating network events for socket 1412
. 2023-05-11 16:16:18.008 Enumerated 1 network events making 1 cumulative events for socket 1412
. 2023-05-11 16:16:18.008 Handling network read event on socket 1412 with error 0
. 2023-05-11 16:16:18.008 Waiting for the server to continue with the initialization
. 2023-05-11 16:16:18.008 Looking for incoming data
. 2023-05-11 16:16:18.008 Looking for network events
. 2023-05-11 16:16:18.008 Password authentication failed
! 2023-05-11 16:16:18.008 Access denied`

For connection over the WinSCP GUI it works perfect with these settings which are also set as default.
![image](https://github.com/cristianst85/QuickConnectPlugin/assets/45741845/ffa6c85c-08dd-4f2b-964a-23b026603f39)

It works also when t trying to connect by cmd:
cmd://"...\WinSCP\WinSCP.exe" username:password@server.com

Can we set the Plugins protocol to ftp /explicit . 
What else can cause the issue?

**Comment by cristianst85** [comment]
Hello.

From the README.md:

Starting with version [0.6.0-rc.1](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.6.0-rc.1) the protocol for WinSCP can be also specified with the additional options. The syntax is as follows: `protocol:{sftp|ftp|scp}` (e.g., `protocol:sftp`). If the protocol is omitted then it defaults to `scp`.

No, at the moment the QuickConnectPlugin cannot pass `/explicit` to WinSCP.

**Comment by cristianst85** [comment]
Why not use SFTP instead? Please note that you also must explicitly specify port 22 with SFTP.

**Comment by feelnrg** [comment]
Hi, thanks for response. 
Where do we have to place the syntax:  protocol:{sftp|ftp|scp} 
Place in Notes after enabled Mapping in Additional Options to Notes. How is the right method?
Just plce it to Notes as protocol:{sftp|ftp|scp} 
or winscp protocol:{sftp|ftp|scp} 

Thanks for support

**Comment by cristianst85** [comment]
That depends on your settings.
You have to place it in the field that `Additional options` is mapped to.

e.g., `linux;protocol:sftp;port:22`

**Comment by cristianst85** [comment]
That depends on your settings.

For example in `QuickConnect` -> `Options...` -> `Map Fields` -> set both `Connection method from` and `Additional options from` to `Notes`. Then in the `Notes` field of your entry add:

`linux;protocol:sftp;port:22` (specifies both the protocol to be used by WinSCP and the port)

or

`linux;protocol:ftp` (uses the default port for FTP, i.e., 21)

**Comment by cristianst85** [comment]
@feelnrg, any updates? Did it work?
