### ISSUE TITLE
Sending -pw option when connecting via telnet

### ISSUE THREAD

**Issue by jtryon** [cristianst85/QuickConnectPlugin#4]
Hi,

Think this might be an easy fix on your end.  When connecting via telnet you should just skip sending the password altogether.  Otherwise the quickconnect via putty fails with:
"the -pw option can only be used with the ssh protocol"

Think this is just due to how telnet sessions tend to take passwords.

**Comment by cristianst85** [comment]
@jtryon, thank you for reporting this.

I've fixed it in the latest [release](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.3.0-rc.2), but it seems now that connecting via Telnet is a two step process:
- launch PuTTY via QuickConnect;
- use Perform Auto-Type.

Also the default auto-type sequence needs to be overridden to `{USERNAME}{ENTER}{PASSWORD}{ENTER}`.
