### ISSUE TITLE
Feature Request: Using Tags

### ISSUE THREAD

**Issue by jtryon** [cristianst85/QuickConnectPlugin#5]
I think it could potentially be useful to scan tags for the protocol to use when connecting as well.
In our case the front end I use for keepass ends up storing this information under a tag such as "ssh" or "rdp".

**Comment by cristianst85** [comment]
If I understand correctly your request I think this is already supported in [latest](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.3.0-rc.2) version - currently on the [dev](https://github.com/cristianst85/QuickConnectPlugin/tree/dev) branch (see [usage](https://github.com/cristianst85/QuickConnectPlugin/tree/dev#usage)).

**Comment by jtryon** [comment]
You're right, this works as intended!  Marking closed.  Thanks.
