### ISSUE TITLE
Override default SSH port

### ISSUE THREAD

**Issue by tarampampam** [cristianst85/QuickConnectPlugin#7]
Hi dude!

Please, say - how i can set up specific ports for ssh connection entries? For example, string for starting putty must have this view:
`D:\some\path\to\PuTTYPortable.exe -ssh -l myUsername -pw myPassword -P 16761 -load "myProfile" 1.2.3.4`

**Comment by cristianst85** [comment]
Hi, @tarampampam.

Overriding the default SSH port is not supported at the moment, but it can be implemented.

**Comment by cristianst85** [comment]
A new version with the requested feature is available for download [here](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.3.0-rc.4) - we are currently on the [dev](https://github.com/cristianst85/QuickConnectPlugin/tree/dev) branch (see [usage](https://github.com/cristianst85/QuickConnectPlugin/tree/dev#usage)).

The default port can be overridden via `Additional options`. Given your example, you'll need to add something like this for your entry: `ssh;session:"myProfile";port:16761`.

Also, don't forget to map `Additional options` (QuickConnect -> Options -> Map Fields) to the corresponding database field.

**Comment by tarampampam** [comment]
Great thx! But now i set this in uri field, and all works fine:

``` cmd
cmd://.\putty\PuTTYPortable.exe -ssh -l {username} -pw {password} -P {S:SSHPort} -load "Default" {S:ServerIPv4}
```
